interface SharedObjectData {
  lock: any;
  lockor: any;
  ulock: any;
  frog: boolean;
  left: boolean;
  wins: number;
  shits: number;
  pill: any[] | number;
  dde: any[] | number;
  gams: number;
  bomb: number;
  deads: number;
  rocks: number;
  cols: any[];
  boss: any[];
  lcomp: any[];
  mwin: any[];
  rox: number;
  icer: number;
  cocks: boolean;
  soff: boolean;
  moff: boolean;
  hard: boolean;
  qqal: string | boolean;
  full: boolean;
  wind: number;
  res: number;
}

class SharedObject {
  static getLocal(arg0: string, arg1: string): SharedObject {
    throw new Error("Method not implemented.");
  }
  data: SharedObjectData;
}

interface SoundObject {
  nam: string;
  s: any;
  looper: boolean;
  looper2: boolean;
  wining: boolean;
}

interface GameRoot {
  firrb: number;
  ittt2: number[];
  ittt3: number[];
  colit: number;
  piller: any[];
  nohead: boolean;
  firrr: number;
  bluf: number;
  luck: number;
  catlives: number;
  shitpenny: boolean;
  whatstart2: boolean;
  chap: number;
  slugeye: number;
  shroom: any;
  donelev: any;
  chesttype: any;
  m: any;
  st1: any;
  st2x: any;
  aloc(): unknown;
  lox: any;
  lcomp: any;
  bossk: any;
  playsp: number;
  minwin: any;
  olda: any;
  knif: any;
  knir: any;
  playersp: number;
  dmusic: any;
  prsk: any;
  prsk2: number;
  black: any;
  p: any;
  ulocker: any;
  unlll: any;
  _currentframe: number;
  winners: number;
  flyss: any;
  amas: boolean;
  wiptz: any;
  ittt5: any;
  ittt4: any;
  ittt6: any;
  ittt10: any;
  ittt8: any;
  colss: number[] | boolean[];
  menu: any;
  old: any;
  createEmptyMovieClip(arg0: string, arg1: number): any;
  noff3: boolean | number;
  noff2: boolean | number;
  noff: boolean | number;
  armor: number;
  notch: boolean;
  bombnext: boolean | number;
  pillfirst: boolean;
  monbb: number;
  vamp: number;
  bmode: number;
  hatmode: number[];
  demonz: number;
  hmode: number;
  horsedown: number;
  eterns: number;
  keys: any;
  firra: number;
  bombs: number;
  altb3: boolean;
  horsem: boolean;
  altb: boolean;
  altb2: boolean;
  switchero: number | boolean;
  swww: number;
  horse: boolean;
  samer: number;
  over: any;
  ittt: any;
  ittt9: any;
  classit: boolean;
  cols: any;
  wtfuuz: any;
  hat: any;
  junxx: number[];
  ittt7: any;
  picers: any;
  pilc: number;
  atrixer: any;
  trixer: any;
  fmode: any;
  trix: number;
  atrix: number;
  map: any;
  ups: any;
  eto: any;
  mmus: any;
  soundy(arg0: string, arg1?: number): any;
  so: any;
  door: number;
  g: any;
  sk: number;
  whatstart: any;
  playerx: number;
  playery: number;
  playcol: any;
  getup: any;
  tell: any;
  mhp: any;
  pinfo: number;
  st2: any;
  mapa: any;
  lasth: any;
  chaf: any;
  itc: any;
  amusic: boolean;
  hp: number;
  soundonce: any; //Record<string, boolean>;
  soundvol: number;
  sz: SoundObject[];
  szz: number;
  bossl: number;
  bossl2: number;
  lev: number;
  chaps: number;
  bossmusic: boolean | number;
  musc: any;
  fade: boolean;
  amusc: SoundObject;
  musicoff: boolean;
  hardmode: boolean;
  res: number;
  hdd: boolean | number;
  paus: any;
  pauss: any;
  men: any;
  hud: any;
  tex: any;
  chala: number;
  altboss2: boolean | number;
  altboss: boolean | number;
  locker: boolean[];
  unl: any;
  nozinc: boolean;
  darky: (intensity: number) => void;
  newstartt: boolean;
  eta: boolean;
  big: boolean;
  darks: boolean;
  altm: boolean;
  double: boolean;
  altchap: any;
  fullhp: boolean;
  bookster: boolean;
  lastdev: any;
  minz: number[];
  us: boolean;
  lastkeeps: number;
  altch: any;
  altsat: boolean;
  kramper: number | boolean;
  beenlev: any[];
  minb: any;
  chamb: any;
  gamb: any;
  sac: any;
  lib: any;
  cus: any;
  boner: any;
  boner2: any;
  shoshop: any;
  cus2: any;
  rax00: any;
  rax01: any;
  rax02: any;
  rax03: any;
  rax04: any;
  rax10: any;
  rax11: any;
  rax12: any;
  rax13: any;
  rax14: any;
  rax20: any;
  rax21: any;
  rax22: any;
  rax23: any;
  rax24: any;
  kep: any;
  mapsize: number;
  rarer: any[];
  levblow: any;
  levit: any;
  specol: any;
  alto: any;
  dropo: any;
  beenlev2: any;
  seenlev: any;
  bomf: any;
  shopa: any;
  liba: any;
  bona: any;
  bona2: any;
  hider: any;
  hiderr: any;
  hider2: any;
  hiderr2: any;
  hid2: any;
  minbb: any;
  gama: any;
  gambb: any;
  chambb: any;
  chama: any;
  shopaz: any;
  bossd: any;
  treasd: any;
  treasd2: any;
  gamaaa: any;
  levcol: any;
  world: any;
  evs: number;
  iter: any;
  devil: any;
  bumkill: any;
  alof: number;
  ceye: any;
  heaven: any;
  nodmg: any;
  hairb: any;
  hide: any;
  hide2: any;
  lastl: any;
  shopl: any;
  bosslv1: any;
  sacb: any;
  libb: any;
  cusb: any;
  sacer: any;
  cuts: any;
  bosss: any;
  bosss2: any;
  trg: any;
  skiner: number;
  intro: boolean | number;
  creskip: boolean;
  etol: boolean;
  coins: number;
  levsav: any[][];
  levz: any[];
  lockor: any[];
  attachMovie: (id: string, name: string, depth: number, initObj?: any) => any;
  _yscale: number;
  _xscale: number;
  _x: number;
  _y: number;
  a: {
    flyshut: number;
    player: any;
    ashut: number;
    mapd: () => void;
    st22: (quality: string | boolean) => void;
    fra: number;
    unpause: boolean;
  };
  gotoAndStop: (frame: string | number) => void;
  getBytesLoaded: () => number;
  getBytesTotal: () => number;
  _quality: string;
  it: number;
}

declare class Sound {
  constructor(target?: any);
  attachSound(soundName: string): void;
  loadSound(soundName: string, streaming: boolean): void;
  start(offset?: number, loops?: number): void;
  setVolume(volume: number): void;
}

declare let doit: any;
declare let showit: any;
declare let random: (max: number) => number;

declare const _root: GameRoot;
declare let so: SharedObject;
declare const Key: any;
declare const mdm: any;
declare const fscommand: any;
declare const getUrl: any;
declare const getTimer: () => number;
declare const _currentframe: number;
declare const passw: string;
declare let cent: number;
declare let linx: boolean;
declare let win: any;
declare let macVersion: any;
declare let lasf: any;
declare let fra: any;
declare let wider: any;
declare let wid: number;
declare let refs: any[][] | any[];
declare let colz: any;
declare let fuk: boolean;
declare let bosm: string;
declare let mvol: number;
declare let lop: number;
declare let checker: any[];
declare let checker1: any[];
declare let checker2: string[];
declare const locker: boolean[];
declare const ulocker: boolean[];
declare let saverr: string;
declare let light: any;
declare let trg2: any;
declare let fra10: any;
declare let qqua: string | boolean;
declare let ala: number;
declare let itb: number;
declare let dark: number;
declare let dda: number;
declare let undark: boolean;
declare let fader: boolean;
declare let colo: any;
declare let nosave: number;
declare let gosave: boolean;
declare let ffs1: boolean;
declare let d: any;
declare let unqua: boolean;
declare let unff2: boolean;
declare let unff: boolean;
declare let overlay2: any;
declare let lastn: string;
declare let mpp: boolean;
declare let v0: number;
declare let v1: any;
declare let v2: any;
declare let v3: any;
declare let trg: any;
declare let _loc0_: any;
declare let f0: any;
declare let f3: any;
declare let o: any;
declare let z: number;
declare let e: any;
declare let f2: any;
declare let hdd: any;
declare let loslol: number;
declare let menubeen: number;
declare let lop2: number;
declare let gof: number;
declare let currUrl: string;
declare let pass: boolean;
declare let st1: string[] | any[];
declare let st2x: string[] | any[];
declare let acnam: string[] | any[];
declare let old: any;
declare let map: any;
declare let overlay: any;
declare let winVersion: number;
declare let _url: string;
declare const flash: any;
declare let chal: number;
declare let f1: any;
declare let a: any;
declare let firsttime: any;
declare let etogo: number;
declare let razor: number;
declare let firra: number;
declare let firrb: number;
declare let ittt: number[];
declare let ittt2: number[];
declare let ittt3: number[];
declare let ittt4: number[];
declare let ittt6: number[];
declare let ittt7: number[];
declare let ittt8: number[];
declare let ittt9: number[];
declare let ittt10: number[];
declare let junxx: number[];
declare let picers: number[];
declare let noff: boolean;
declare let noff2: boolean;
declare let noff3: boolean;
declare let alof: number;
declare let pillfirst: boolean;
declare let bombnext: boolean;
declare let notch: boolean;
declare let lastkeeps: number;
declare let armor: number;
declare let pilc: any;
declare let trix: any;
declare let atrix: any;
declare let vamp: number;
declare let monbb: number;
declare let horsedown: number;
declare let it: number;
declare let fmode: number;
declare let hmode: number;
declare let bmode: number;
declare let demonz: number;
declare let bookster: boolean;
declare let hatmode: number[];
declare let wtfuuz: boolean;
declare let coins: number;
declare let bombs: number;
declare let keys: number;
declare let lastdev: any;
declare let minz: number[];
declare let sk: number;
declare let eto: number;
declare let eterns: number;
declare let endrooms: any[];
declare let hardx: any[][];
declare let hardy: any[][];
declare let blorz: any;
declare let _X: number;
declare let _Y: number;
declare let grox: any;
declare let gro: any;
declare let i: any;
declare let ball: any[];
declare let lastcraf: number;
declare let highs: any;
declare let lastcra: number;
declare let chama: number;
declare let chamb: number;
declare let poli: boolean;
declare let f11: any;
declare let lasth: number;
declare let telf: any;
declare let playsave: number;
declare let unic: number;
declare let horse: number;
declare let dec: number;
declare let coinl: any;
declare let v: any;
declare let leg: any[];
declare let enf: number;
declare let slow: number;
declare let fra2: boolean;
declare let spidboss: boolean;
declare let roxx: number;
declare let gibb: number;
declare let bull: any;
declare let f13: any;
declare let trris: number;
declare let f12: any;
declare let f4: any;
declare let rowz: number;
declare let gridx: number;
declare let gridy: number;
declare let gridv: number;
declare let gridmax: number;
declare let grid: any;
declare let grid2: any;
declare let flyer: number;
declare let ballz: number;
declare let namer2: string;
declare let f18: boolean;
declare let f7: any;
declare let helpss: number;
declare let sloto: any;
declare let refl: any[];
declare let sati: any;
declare let mhelps: number;
declare let gurdy: boolean;
declare let spispaw: boolean;
declare let kkk: boolean;
declare let chestox: number;
declare let chestoy: number;
declare let f10: any;
declare let shiz: any[];
declare let altb: any[];
declare let mpiece: any;
declare let qq: string;
declare let minx: number;
declare let maxy: number;
declare let miny: number;
declare let spuz: number;
declare let rply: any;
declare let mheart: any;
declare let savv: number;
declare let clevc: any[];
declare let ref: any[];
declare let cus: boolean;
declare let b1: boolean;
declare let noho: boolean;
declare let dang: boolean;
declare let parz: number;
declare let namer: string;
declare let par: any[];
declare let pillef: number;
declare let pacman: boolean;
declare let lib: number;
declare let lows: any;
declare let momdown: number;
declare let levz: any[];
declare let door: any[];
declare let d1: any;
declare let d2: any;
declare let d3: any;
declare let d4: any;
declare let acts: any[];
declare let acts2: any[];
declare let ups: any[];
declare const _this: any;
declare let timer: any[];
declare let alltimer: any[];
declare let player: any;
declare let altboss: boolean | number;
declare let doub: boolean;
declare let f5: any;
declare let f6: any;
declare let cra1: number;
declare let cra2: number;
declare let demon: number;
declare let sob: number;
declare let chaf: number;
declare let blood: any;
declare let bloc: any;
declare let poi: any;
declare let shad: any;
declare let org: any;
declare let shaz: any;
declare let maxx: any;
declare let trrisss: number;
declare let mome: number;
declare let moml: number;
declare let f44: any;
declare let webs: any[];
declare let f55: number;
declare let relf: boolean | number;
declare let dblock: any;
declare let tiles: any;
declare let roxx2: number;
declare let bomf: any[];
declare let big: number;
declare let ashut: number;
declare let lastbo: number;
declare let nosp: boolean;
declare let spac: boolean;
declare let nospo: number;
declare let lchaf: number;
declare let chax: number;
declare let chay: number;
declare let bosser: number;
declare let help: number;
declare let helps: number;
declare let slugsp: number;
declare let lass: number;
declare let siz: number;
declare let lars: number;
declare let xpp: number;
declare let maxxx: any;
declare let llev: number[];
declare let llev2: number[];
declare let specol: number[][];
declare let specol2: any[];
declare let levn: (string | number)[];
declare let levn2: (string | number)[];
declare let gridxs: number;
declare let gridys: number;
declare let hdx: number;
declare let etols: number;
declare let rage: number;
declare let combis: number;
declare let lusts: number;
declare let rag: number;
declare let thistern: number;
declare let curss: string;
declare let fuckup: number;
declare let f14: any;
declare let f15: number;
declare let brr: any[];
declare let brr2: any[];
declare let wtftex: any;
declare let gameover: number;
declare let justnow: number;
declare let itc: number[];
declare let wtfps2: number;
declare let wtfps: number;
declare let wtfpsh: boolean;
declare let wtff: number;
declare let secol: number;
declare let minions: number;
declare let flyby: number;
declare let mom: any[];
declare let worm: any[];
declare let mags: any[];
declare let f8: any;
declare let bigone: boolean;
declare let inl: any;
declare let inem: boolean;
declare let altgo: boolean;
declare let b: any;
declare let xenf: number;
declare let yenf: number;
declare let gxe: number;
declare let gye: number;
declare let mux: number;
declare let p180: number;
declare let p10: number;
declare let sizes: number[];
declare let masses: number[];
declare let hps: number[];
declare let hard: number[];
declare let hops: any[];
declare let wb: number[];
declare let it1: boolean[];
declare let watz: number;
declare let hearts: number[];
declare let masks: number[];
declare let noetern: boolean;
declare let gospo: boolean;
declare let hitc: number;
declare let hitcc: number;
declare let bossdmg: boolean;
declare let bgg: any;
declare let gut: any;
declare let kogs: number[];
declare let Mouse: any;
declare let mouseListener: any;
declare let md: boolean;
declare let unpause: boolean;
declare let axenf: number;
declare let ayenf: number;
declare let olfx: number;
declare let olfy: number;
declare let shutdoor: number;
declare let ffly: number;
declare let fiz: number;
declare let etux: number;
declare let f: any;
declare let nextbo: boolean;
declare let emosound: boolean;
declare let flyby2: number;
declare let flyby3: number;
declare let flyby4: number;
declare let plo: number;
declare let lastxy: number;
declare let lastxx: number;
declare let tictic: any;
declare let nocharge: number;
declare let mhpp: number;
declare let ahpp: number;
declare let red: number;
declare let blue: number;
declare let plox: number;
declare let splat: any;
declare let f9: any;
declare let blackout: boolean | number;
declare let lod: number;
declare let tot: number;
declare let hud: any;
declare let _quality: string | boolean;
declare let intro: boolean | number;
declare let treas: any;
declare let flox: any;
declare let spezz: any;
declare let allets: any;
declare let noet: any;
declare let trg3: any;
declare let trg4: any;
declare let f155: any;
declare let wtfe: any;
declare let gobo: any;
declare let groso: any;
declare let nomag: any;
declare let boils: any;
declare let swag: any;
declare let chubber: any;
declare let salefail: any;
declare let babymode: any;
declare let trrisx: any;
declare let plh: any;
declare let mhheart: any;
declare let healo: any;
declare let lastk: any;
declare let plah: any;
declare let bluf: any;
declare let holz: any;
declare let blufer: any;
declare let farter: any;
declare let tar: any;
declare let gofind: any;
declare let crater: any;
declare let nomore: any;
declare let bggg: any;
declare let yyo: any;
declare let sat: any;
declare let gopill: any;
declare let lads: any;
declare let ypp: any;
declare let xppp: any;
declare let yppp: any;
declare let nogo: any;
declare let v5: any;
declare let nogridyet: any;
declare let testarr: any;
declare let v4: any;
declare let gochar: any;
declare let f33: any;
declare let maxp: any;
declare let cowss: any;
declare let nohit: any;
declare let purr: any;
declare let ablub: any;
declare let pilll: any;
declare let dodo: any;
declare let freez: any;
declare let pub: any;
declare let playslow: any;
declare let beamer: any;
declare let chestopen: any;
declare let lastspin: any;
declare let plxxx: any;
declare let plyyx: any;
declare let plffff: any;
declare let siz2: any;
declare let v6: any;
declare let trriss: any;
declare let paccer: any;
declare let dbird: any;
declare let vv: any;
declare let xbewenf: any;
declare let ybewenf: any;
declare let bewenf: any;
declare let decer: any;
declare let xxenf: any;
declare let yyenf: any;
declare let speed: any;
declare let lofo: any;
declare let mins: any;
declare let dang2: any;
declare let nobob: any;
declare let llss: any;
declare let chaz: any;
declare let bombdrop: any;
declare let drop: any;
declare let folz: any;
declare let lassd: any;
declare let plox1: any;
declare let ablufer: any;
declare let blub: any;
declare let blufb: any;
declare let fra3: any;
declare let fra5: any;
declare let flys: any;
declare let fll: any;
declare let lff: any;
declare let follow: any;
declare let lastbb: any;
declare let lastbbb: any;
declare let isaaaac: any;
declare let bull2: any;
declare let wormet: any;
declare let momet: any;
declare let magget: any;
declare let anarch: any;
declare let analt: any;
declare let killa: any;
declare let splaz: any;
declare let sacri: any;
declare let bossheart: any;
declare let flyshut: any;
declare let fonter: any;
declare let minsber: any;
declare let bollocks: any;
declare let ea: any;
declare let sloww: any;
declare let dukes: any;
declare let duke: any;
declare let duked: any;
declare let nofun: any;
declare let tgr2: any;
declare let slug: any;
declare let trrisp: any;
declare let egggs: any;
declare let whuf: any;
declare let bossrep: any;
declare let trris2: any;
declare let magss: any;
declare let firstmag: any;
declare let lastpoop: any;
declare let oldm: any;
declare let randrom: any;
declare let playx: any;
declare let playy: any;
declare let lpf: any;
declare let tier: any;
declare let momstate: any;
declare let lmo: any;
declare let xenf1: any;
declare let trg5: any;
declare let wormfo: any;
declare let death: any;
declare let lastlarx: any;
declare let lastlary: any;
declare let lastlar: any;
declare let scare: any;
declare let removeMovieClip: any;
declare let bollocks2: any;
declare let gxee: any;
declare let c: any;
declare let bollocks3: any;
declare let hhorse: any;
declare let turdb: any;
declare let turdz: any;
declare let ladder: any;
declare let lastf1: any;
declare let lastf2: any;
declare let roty: any;
declare let lasx: any;
declare let lasy: any;
declare let brim: any;
declare let v111: any;
declare let keyhole: any;
declare let keypoww: any;
declare let keypow: any;
declare let alad: any;
declare let roller: any;
declare let hfff: any;
declare let horsx: any;
declare let horsy: any;
declare let goper: any;
declare let keyd: any;
declare let bodd: any;
declare let bibs: any;
declare let bible: any;
declare let bra: any;
declare let laser: any;
declare let bomberfail: any;
declare let lastx: any;
declare let lasty: any;
declare let _xmouse: any;
declare let _ymouse: any;
declare let nomove: any;
declare let knil: any;
declare let knill: any;
declare let knife: any;
declare let nohat: any;
declare let facer: any;
declare let chaaf: any;
declare let pacoo: any;
declare let plxx: any;
declare let bgg2: any;
declare let playfirst: any;
declare let co: any;
declare let bumz: any;
declare let cats: any;
declare let catss: any;
declare let monb: any;
declare let monb2: any;
declare let monb3: any;
declare let monb4: any;
declare let meats: any;
declare let meats2: any;
declare let eyepie: any;
declare let hairb: any;
declare let holp: any;
declare let knip: any;
declare let ggho: any;
declare let ggho2: any;
declare let dad: any;
declare let magsss: any;
declare let keyo: any;
declare let hudder: any;
declare let resee: any;
declare let sadfa: any;
declare let boss: any;
declare let souldrop: any;
declare let cock: any;
declare let openss: any;
declare let drawer: any;
declare let unspace: any;
declare let unlo: any;
declare let apau: any;
declare let bggg2: any;
declare let nomute: any;
declare let fade: any;
declare let introz: any;
declare let sz: any;
declare let nozinc: any;
declare let tests: any;
